# version: '3'
# services:
#   angular-app:
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#     volumes:
#       - .:/app
#     ports:
#       - "4200:4200"
#     command: npm start
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    container_name: app
